### ISSUE TITLE
Good Layout for Blog

### ISSUE THREAD

**Issue by matematikaadit** [matematikaadit/matematikaadit.github.io#21]
In this Issue I'll collect some good layout that could be used for a blog.

For our first subject, I'll present Russ Cox Blog at http://research.swtch.com/

![russ-cox-blog](https://f.cloud.github.com/assets/311326/1623088/436630ae-56af-11e3-89e1-59dc8c7b8af5.png)

In this screenshot, I add some addition markup using Chrome inspector. Here the CSS:

``` css
#extra, body {
    max-width: 600px;
    margin-left: auto;
    margin-right: auto;
}
```

With the `#extra` being some div that I put on the `.header`. It's pleasant to read. Has good font choice. And good comment display.

![comment-at-russ-cox](https://f.cloud.github.com/assets/311326/1623125/fd4477b0-56af-11e3-8893-db62ad5d4f5a.png)

Maybe I'll choose this for my [atklite](http://atklite.herokuapp.com) project.
